# docker-compose.prod.yml
# Use of the published Docker Hub image
#
# Usage:
#   DOCKERHUB_USERNAME=<USERNAME> VERSION=v<VERSION> docker compose -f docker-compose.prod.yml up -d
services:
  app:
    image: ${DOCKERHUB_USERNAME:-username}/mathtrainerdotnet:${VERSION:-latest}
    container_name: mathtrainer
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - mathtrainer-data:/app/data

volumes:
  mathtrainer-data:
    name: mathtrainer-data
